-- Run this once in the Supabase SQL Editor for this project.
-- Adds a table admins use to manually block a car's dates (maintenance,
-- an off-platform rental, etc.) separately from real bookings.

create table if not exists car_unavailability (
  id bigint generated by default as identity primary key,
  car_id bigint not null references cars(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint car_unavailability_date_order check (end_date >= start_date)
);

create index if not exists car_unavailability_car_id_idx on car_unavailability(car_id);

alter table car_unavailability enable row level security;

-- Anyone can read blocked ranges -- the public search/booking flow needs this
-- to hide unavailable cars and reject conflicting bookings.
create policy "Public can read car unavailability"
  on car_unavailability for select
  using (true);

-- Only admins (profiles.role = 'admin') can create/edit/delete blocks.
-- If your other admin-writable tables (e.g. "cars") don't have RLS enabled,
-- or use a simpler/looser policy, mirror that here instead for consistency --
-- this is just a secure-by-default starting point.
create policy "Admins can manage car unavailability"
  on car_unavailability for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
